# Exploring Alpha Vantage API

### Imports- **Run First**

In [2]:
#open file with your API key
with open('Alpha_Vintage_API_Key.txt') as file:
    API_key = file.read()
API_key = API_key.strip()

In [3]:
#import libraries
from alpha_vantage.timeseries import TimeSeries

import requests
from bs4 import BeautifulSoup

import pandas as pd
import io

In [4]:
#build TimeSeries variable from Alpha Vantage API
ts1 = TimeSeries(key = API_key)

### How to put stock data into a DataFrame

#### Requests Method

In [24]:
#get weekly stock data of Apple in DataFrame format
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=AAPL&apikey=' + str(API_key) + "&datatype=csv"
response = requests.get(url).content

data= pd.read_csv(io.StringIO(response.decode("utf-8")))
print(data)

       timestamp     open    high     low   close     volume
0     2024-02-01  192.010  192.20  183.82  186.86  223358203
1     2024-01-26  192.300  196.38  191.94  192.42  255368848
2     2024-01-19  182.160  191.95  180.30  191.56  259829213
3     2024-01-12  182.085  187.05  181.50  185.92  238385377
4     2024-01-05  187.150  188.44  180.17  181.18  275083628
...          ...      ...     ...     ...     ...        ...
1260  1999-12-10  114.560  118.00   99.00  103.00   25152800
1261  1999-12-03   94.250  115.56   93.25  115.00   28046300
1262  1999-11-26   91.750   95.50   88.50   95.06    9757600
1263  1999-11-19   89.620   94.75   88.06   92.44   13711000
1264  1999-11-12   87.750   97.73   86.75   90.62   25776200

[1265 rows x 6 columns]

In [ ]:
#get head of data
data.head(10)

#### Python Package Method

In [22]:
#store Apple stock intraday data in data and meta_data variables
apple1, meta_data=ts1.get_intraday("AAPL")

In [26]:
#print meta_data
print(meta_data)

{'1. Information': 'Intraday (15min) open, high, low, close prices and volume', '2. Symbol': 'AAPL', '3. Last Refreshed': '2024-02-01 19:45:00', '4. Interval': '15min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}

In [21]:
#print data
print(apple1)

{'2024-02-01 19:45:00': {'1. open': '181.4300', '2. high': '181.6000', '3. low': '181.2100', '4. close': '181.4500', '5. volume': '138032'}, '2024-02-01 19:30:00': {'1. open': '181.1000', '2. high': '181.4300', '3. low': '181.0200', '4. close': '181.4300', '5. volume': '94512'}, '2024-02-01 19:15:00': {'1. open': '181.0600', '2. high': '181.2000', '3. low': '181.0000', '4. close': '181.1500', '5. volume': '81422'}, '2024-02-01 19:00:00': {'1. open': '180.9200', '2. high': '181.1000', '3. low': '180.7900', '4. close': '181.0800', '5. volume': '85198'}, '2024-02-01 18:45:00': {'1. open': '180.9500', '2. high': '181.2500', '3. low': '180.8200', '4. close': '180.8850', '5. volume': '124197'}, '2024-02-01 18:30:00': {'1. open': '180.7500', '2. high': '180.9500', '3. low': '180.6000', '4. close': '180.9000', '5. volume': '144110'}, '2024-02-01 18:15:00': {'1. open': '180.6600', '2. high': '180.9700', '3. low': '180.4600', '4. close': '180.8000', '5. volume': '139529'}, '2024-02-01 18:00:00': {'1. open': '180.6100', '2. high': '181.3700', '3. low': '180.2800', '4. close': '180.6600', '5. volume': '325083'}, '2024-02-01 17:45:00': {'1. open': '181.5010', '2. high': '181.8700', '3. low': '180.2100', '4. close': '180.6100', '5. volume': '658277'}, '2024-02-01 17:30:00': {'1. open': '184.0200', '2. high': '184.3900', '3. low': '179.1000', '4. close': '181.5000', '5. volume': '2137734'}, '2024-02-01 17:15:00': {'1. open': '183.3000', '2. high': '185.7800', '3. low': '182.6000', '4. close': '184.0200', '5. volume': '831516'}, '2024-02-01 17:00:00': {'1. open': '184.7100', '2. high': '184.8800', '3. low': '182.5000', '4. close': '183.3000', '5. volume': '667747'}, '2024-02-01 16:45:00': {'1. open': '183.7400', '2. high': '189.9220', '3. low': '174.4630', '4. close': '184.7100', '5. volume': '2636333'}, '2024-02-01 16:30:00': {'1. open': '188.5000', '2. high': '191.8100', '3. low': '181.5000', '4. close': '183.7000', '5. volume': '3608532'}, '2024-02-01 16:15:00': {'1. open': '187.5250', '2. high': '188.8300', '3. low': '186.2920', '4. close': '188.5000', '5. volume': '541456'}, '2024-02-01 16:00:00': {'1. open': '186.8900', '2. high': '196.0900', '3. low': '186.2100', '4. close': '187.5500', '5. volume': '13184687'}, '2024-02-01 15:45:00': {'1. open': '186.8150', '2. high': '186.9500', '3. low': '186.3600', '4. close': '186.8900', '5. volume': '5000330'}, '2024-02-01 15:30:00': {'1. open': '186.6500', '2. high': '186.9050', '3. low': '186.5000', '4. close': '186.8200', '5. volume': '1843335'}, '2024-02-01 15:15:00': {'1. open': '186.6200', '2. high': '186.8000', '3. low': '186.5500', '4. close': '186.6600', '5. volume': '1529424'}, '2024-02-01 15:00:00': {'1. open': '186.4700', '2. high': '186.7000', '3. low': '186.2800', '4. close': '186.6200', '5. volume': '1837522'}, '2024-02-01 14:45:00': {'1. open': '186.3150', '2. high': '186.6200', '3. low': '186.3150', '4. close': '186.4750', '5. volume': '1419265'}, '2024-02-01 14:30:00': {'1. open': '185.9800', '2. high': '186.4300', '3. low': '185.8810', '4. close': '186.3150', '5. volume': '1160772'}, '2024-02-01 14:15:00': {'1. open': '185.8200', '2. high': '186.1550', '3. low': '185.7600', '4. close': '185.9750', '5. volume': '1051975'}, '2024-02-01 14:00:00': {'1. open': '185.8000', '2. high': '186.1100', '3. low': '185.5500', '4. close': '185.8150', '5. volume': '1244358'}, '2024-02-01 13:45:00': {'1. open': '185.3800', '2. high': '185.9600', '3. low': '185.3800', '4. close': '185.7950', '5. volume': '972119'}, '2024-02-01 13:30:00': {'1. open': '185.7400', '2. high': '185.9000', '3. low': '185.2600', '4. close': '185.3790', '5. volume': '1147789'}, '2024-02-01 13:15:00': {'1. open': '185.9800', '2. high': '186.0700', '3. low': '185.6500', '4. close': '185.7300', '5. volume': '888107'}, '2024-02-01 13:00:00': {'1. open': '186.1300', '2. high': '186.1900', '3. low': '185.5700', '4. close': '185.9900', '5. volume': '1045196'}, '2024-02-01 12:45:00': {'1. open': '185.8200', '2. high': '186.4400', '3. low': '185.8200', '4. close': '186.1200', '5. volume': '1425807'}, '2024-02-01 12:30:00': {'1. open': '185.8900', '2. high': '185.9400', '3. low': '185.6400', '4. close': '185.8250', '5. volume': '1062789'}, '2024-02-01 12:15:00': {'1. open': '186.0100', '2. high': '186.1000', '3. low': '185.8100', '4. close': '185.8900', '5. volume': '972082'}, '2024-02-01 12:00:00': {'1. open': '185.6800', '2. high': '186.2950', '3. low': '185.6600', '4. close': '186.0050', '5. volume': '1476224'}, '2024-02-01 11:45:00': {'1. open': '185.6650', '2. high': '185.8690', '3. low': '185.5600', '4. close': '185.6820', '5. volume': '934069'}, '2024-02-01 11:30:00': {'1. open': '185.3900', '2. high': '185.8950', '3. low': '185.3600', '4. close': '185.6650', '5. volume': '1240403'}, '2024-02-01 11:15:00': {'1. open': '185.8200', '2. high': '185.9100', '3. low': '185.3400', '4. close': '185.3950', '5. volume': '1194169'}, '2024-02-01 11:00:00': {'1. open': '185.3700', '2. high': '186.0700', '3. low': '185.2900', '4. close': '185.8200', '5. volume': '1338452'}, '2024-02-01 10:45:00': {'1. open': '186.0700', '2. high': '186.3100', '3. low': '185.3500', '4. close': '185.3710', '5. volume': '1655675'}, '2024-02-01 10:30:00': {'1. open': '186.1200', '2. high': '186.3000', '3. low': '185.9300', '4. close': '186.0650', '5. volume': '1627549'}, '2024-02-01 10:15:00': {'1. open': '185.7400', '2. high': '186.1800', '3. low': '185.5700', '4. close': '186.1050', '5. volume': '1975195'}, '2024-02-01 10:00:00': {'1. open': '185.4600', '2. high': '185.9900', '3. low': '184.9000', '4. close': '185.7420', '5. volume': '2039948'}, '2024-02-01 09:45:00': {'1. open': '185.2100', '2. high': '185.5000', '3. low': '184.6200', '4. close': '185.5000', '5. volume': '2210217'}, '2024-02-01 09:30:00': {'1. open': '183.9850', '2. high': '185.6400', '3. low': '183.8200', '4. close': '185.2200', '5. volume': '4666007'}, '2024-02-01 09:15:00': {'1. open': '185.5800', '2. high': '185.5800', '3. low': '183.8800', '4. close': '184.1000', '5. volume': '280438'}, '2024-02-01 09:00:00': {'1. open': '185.3000', '2. high': '185.6900', '3. low': '185.2500', '4. close': '185.5100', '5. volume': '66009'}, '2024-02-01 08:45:00': {'1. open': '185.5700', '2. high': '186.9900', '3. low': '185.1300', '4. close': '185.3100', '5. volume': '52496'}, '2024-02-01 08:30:00': {'1. open': '185.5500', '2. high': '185.9200', '3. low': '185.5200', '4. close': '185.5700', '5. volume': '74337'}, '2024-02-01 08:15:00': {'1. open': '185.6000', '2. high': '185.6000', '3. low': '185.3000', '4. close': '185.5350', '5. volume': '30302'}, '2024-02-01 08:00:00': {'1. open': '185.4800', '2. high': '186.0900', '3. low': '184.4000', '4. close': '185.5300', '5. volume': '924337'}, '2024-02-01 07:45:00': {'1. open': '185.6700', '2. high': '185.8200', '3. low': '185.6600', '4. close': '185.7000', '5. volume': '12347'}, '2024-02-01 07:30:00': {'1. open': '185.6600', '2. high': '185.7600', '3. low': '185.5000', '4. close': '185.7600', '5. volume': '10631'}, '2024-02-01 07:15:00': {'1. open': '185.5800', '2. high': '185.8500', '3. low': '185.4600', '4. close': '185.6300', '5. volume': '25672'}, '2024-02-01 07:00:00': {'1. open': '185.6300', '2. high': '185.6600', '3. low': '185.4300', '4. close': '185.6100', '5. volume': '18186'}, '2024-02-01 06:45:00': {'1. open': '185.2600', '2. high': '185.8800', '3. low': '185.1900', '4. close': '185.6300', '5. volume': '27355'}, '2024-02-01 06:30:00': {'1. open': '185.1200', '2. high': '185.2900', '3. low': '185.0600', '4. close': '185.1900', '5. volume': '6269'}, '2024-02-01 06:15:00': {'1. open': '185.4500', '2. high': '185.4800', '3. low': '185.0700', '4. close': '185.1800', '5. volume': '9316'}, '2024-02-01 06:00:00': {'1. open': '185.6900', '2. high': '185.7300', '3. low': '185.4000', '4. close': '185.4600', '5. volume': '5059'}, '2024-02-01 05:45:00': {'1. open': '185.4000', '2. high': '185.7000', '3. low': '185.4000', '4. close': '185.7000', '5. volume': '13024'}, '2024-02-01 05:30:00': {'1. open': '185.3400', '2. high': '185.4000', '3. low': '185.3200', '4. close': '185.4000', '5. volume': '6615'}, '2024-02-01 05:15:00': {'1. open': '185.3500', '2. high': '185.4000', '3. low': '185.3200', '4. close': '185.3400', '5. volume': '3050'}, '2024-02-01 05:00:00': {'1. open': '185.4900', '2. high': '185.5000', '3. low': '185.3000', '4. close': '185.4000', '5. volume': '11062'}, '2024-02-01 04:45:00': {'1. open': '185.5200', '2. high': '185.6000', '3. low': '185.4900', '4. close': '185.4900', '5. volume': '5045'}, '2024-02-01 04:30:00': {'1. open': '185.7700', '2. high': '185.8000', '3. low': '185.4000', '4. close': '185.5400', '5. volume': '8354'}, '2024-02-01 04:15:00': {'1. open': '185.8400', '2. high': '185.8800', '3. low': '185.7200', '4. close': '185.7700', '5. volume': '3219'}, '2024-02-01 04:00:00': {'1. open': '186.5000', '2. high': '186.5000', '3. low': '185.4900', '4. close': '185.8200', '5. volume': '9078'}, '2024-01-31 19:45:00': {'1. open': '185.5600', '2. high': '185.7700', '3. low': '185.4000', '4. close': '185.6800', '5. volume': '14001'}, '2024-01-31 19:30:00': {'1. open': '185.4000', '2. high': '185.5800', '3. low': '185.3000', '4. close': '185.5600', '5. volume': '9729'}, '2024-01-31 19:15:00': {'1. open': '185.4000', '2. high': '185.4500', '3. low': '185.1300', '4. close': '185.3500', '5. volume': '8007'}, '2024-01-31 19:00:00': {'1. open': '185.3800', '2. high': '185.4500', '3. low': '185.2200', '4. close': '185.4400', '5. volume': '8043'}, '2024-01-31 18:45:00': {'1. open': '185.2800', '2. high': '185.4500', '3. low': '185.1300', '4. close': '185.3800', '5. volume': '16025'}, '2024-01-31 18:30:00': {'1. open': '185.2500', '2. high': '185.4000', '3. low': '185.0400', '4. close': '185.2650', '5. volume': '5143'}, '2024-01-31 18:15:00': {'1. open': '184.9900', '2. high': '185.2900', '3. low': '184.4000', '4. close': '185.2800', '5. volume': '9426'}, '2024-01-31 18:00:00': {'1. open': '185.1200', '2. high': '185.3600', '3. low': '184.8600', '4. close': '184.9850', '5. volume': '7961'}, '2024-01-31 17:45:00': {'1. open': '185.2200', '2. high': '185.2900', '3. low': '184.8000', '4. close': '185.1000', '5. volume': '8739'}, '2024-01-31 17:30:00': {'1. open': '185.1500', '2. high': '185.2900', '3. low': '185.0200', '4. close': '185.2200', '5. volume': '9019'}, '2024-01-31 17:15:00': {'1. open': '185.0000', '2. high': '185.2600', '3. low': '184.8100', '4. close': '185.2000', '5. volume': '16130'}, '2024-01-31 17:00:00': {'1. open': '184.8700', '2. high': '185.0400', '3. low': '184.4000', '4. close': '185.0100', '5. volume': '224784'}, '2024-01-31 16:45:00': {'1. open': '185.0400', '2. high': '187.8290', '3. low': '175.7560', '4. close': '184.9000', '5. volume': '110698'}, '2024-01-31 16:30:00': {'1. open': '185.5900', '2. high': '185.7000', '3. low': '184.4000', '4. close': '185.0100', '5. volume': '194792'}, '2024-01-31 16:15:00': {'1. open': '185.8300', '2. high': '185.9300', '3. low': '184.4000', '4. close': '185.5700', '5. volume': '85599'}, '2024-01-31 16:00:00': {'1. open': '184.4400', '2. high': '186.3950', '3. low': '183.8200', '4. close': '185.8900', '5. volume': '21384237'}, '2024-01-31 15:45:00': {'1. open': '185.1100', '2. high': '185.3200', '3. low': '184.3500', '4. close': '184.3600', '5. volume': '4867072'}, '2024-01-31 15:30:00': {'1. open': '185.5200', '2. high': '185.5890', '3. low': '185.0100', '4. close': '185.1150', '5. volume': '1561759'}, '2024-01-31 15:15:00': {'1. open': '185.5000', '2. high': '185.6500', '3. low': '185.0350', '4. close': '185.5200', '5. volume': '1502358'}, '2024-01-31 15:00:00': {'1. open': '185.9800', '2. high': '186.0300', '3. low': '185.0700', '4. close': '185.5050', '5. volume': '1948887'}, '2024-01-31 14:45:00': {'1. open': '186.6750', '2. high': '186.9400', '3. low': '185.9100', '4. close': '185.9700', '5. volume': '1445376'}, '2024-01-31 14:30:00': {'1. open': '185.6700', '2. high': '186.7900', '3. low': '185.4600', '4. close': '186.6630', '5. volume': '1811261'}, '2024-01-31 14:15:00': {'1. open': '185.8800', '2. high': '185.8850', '3. low': '185.4460', '4. close': '185.6700', '5. volume': '1055616'}, '2024-01-31 14:00:00': {'1. open': '186.1700', '2. high': '186.3200', '3. low': '185.2600', '4. close': '185.8800', '5. volume': '1610006'}, '2024-01-31 13:45:00': {'1. open': '186.3400', '2. high': '186.5300', '3. low': '186.1000', '4. close': '186.1800', '5. volume': '910252'}, '2024-01-31 13:30:00': {'1. open': '186.1700', '2. high': '186.3600', '3. low': '186.1530', '4. close': '186.3200', '5. volume': '807174'}, '2024-01-31 13:15:00': {'1. open': '186.1950', '2. high': '186.3500', '3. low': '186.0750', '4. close': '186.1600', '5. volume': '752400'}, '2024-01-31 13:00:00': {'1. open': '186.3300', '2. high': '186.4400', '3. low': '186.1400', '4. close': '186.1900', '5. volume': '789495'}, '2024-01-31 12:45:00': {'1. open': '186.0350', '2. high': '186.3400', '3. low': '185.9100', '4. close': '186.3250', '5. volume': '885785'}, '2024-01-31 12:30:00': {'1. open': '186.0800', '2. high': '186.1800', '3. low': '185.8330', '4. close': '186.0380', '5. volume': '869409'}, '2024-01-31 12:15:00': {'1. open': '185.9650', '2. high': '187.0000', '3. low': '185.8300', '4. close': '186.0900', '5. volume': '1046464'}, '2024-01-31 12:00:00': {'1. open': '185.6850', '2. high': '185.9700', '3. low': '185.6120', '4. close': '185.9500', '5. volume': '839760'}, '2024-01-31 11:45:00': {'1. open': '185.6250', '2. high': '185.8600', '3. low': '185.4200', '4. close': '185.6850', '5. volume': '892679'}, '2024-01-31 11:30:00': {'1. open': '185.7200', '2. high': '185.7700', '3. low': '185.4200', '4. close': '185.6250', '5. volume': '900272'}, '2024-01-31 11:15:00': {'1. open': '185.6750', '2. high': '185.8700', '3. low': '185.3750', '4. close': '185.7200', '5. volume': '1064624'}, '2024-01-31 11:00:00': {'1. open': '185.3000', '2. high': '185.7200', '3. low': '185.2950', '4. close': '185.6850', '5. volume': '1039491'}}

In [30]:
#store data into a DataFrame
df_meta_data=pd.DataFrame(apple1).transpose().reset_index()
df_meta_data.head()

                 index   1. open   2. high    3. low  4. close 5. volume
0  2024-02-01 19:45:00  181.4300  181.6000  181.2100  181.4500    138032
1  2024-02-01 19:30:00  181.1000  181.4300  181.0200  181.4300     94512
2  2024-02-01 19:15:00  181.0600  181.2000  181.0000  181.1500     81422
3  2024-02-01 19:00:00  180.9200  181.1000  180.7900  181.0800     85198
4  2024-02-01 18:45:00  180.9500  181.2500  180.8200  180.8850    124197

In [ ]:
#Bring in data in DataFrame format

In [ ]:
# display new intraday stock data

In [ ]:
#get full amount of intraday stock data for data and meta_data

In [ ]:
#print meta_data

In [ ]:
#print data with reset index